### ISSUE TITLE
Edit KanBan Board to fit our teams needs

### ISSUE THREAD

**Issue by HubbbaBubbba** [HubbbaBubbba/StackOps#2]
Add/modify the project CIS Database to help the team be able to smoothly transition each task assigned

**Comment by HubbbaBubbba** [comment]
Might update more in the future. With have all team members check to see if it has all of the things they need to complete their task.

**Comment by laurenmalone01** [comment]
update to add urgency and animals tags

**Comment by HubbbaBubbba** [comment]
Ask Cumbie about tags
