### ISSUE TITLE
render link is broken

### ISSUE THREAD

**Issue by laurenmalone01** [HubbbaBubbba/StackOps#35]
![Screenshot (127)](https://user-images.githubusercontent.com/97190412/235272296-07166444-b8bd-43a6-ac97-29b4684e932a.png)

**Comment by barrycumbie** [comment]
I mean...just stopped?

Do other renders work (other teams...listed in a wiki in crispy sniffle) ( does crispy sniffle work?)

Was there a recent commit?

**Comment by barrycumbie** [comment]
Also...

Render build logs? 

Works local?

**Comment by laurenmalone01** [comment]
sooo....its a render issue. and it is happening to other teams renders.
the code works locally. 
![Screenshot (128)](https://user-images.githubusercontent.com/97190412/235278378-72c1721e-024b-48ff-b888-e0952aa1ec37.png)

**Comment by barrycumbie** [comment]
Looks resolved. Maybe render just doing some housekeeping.

**Comment by laurenmalone01** [comment]
works now.
