### ISSUE TITLE
Get website on Render and add link to repo/Connect Cumbie

### ISSUE THREAD

**Issue by HubbbaBubbba** [HubbbaBubbba/StackOps#5]
Make sure that the app is successfully deployed on render.

Add link to website of repo.

Make sure Cumbie sees this.

Tip: if it isn't deploying properly, try the manual deploy button on render.

**Comment by laurenmalone01** [comment]
Finished connect db and repo to render. Working app on render

**Comment by HubbbaBubbba** [comment]
Added Cumbie as collaborator
