### ISSUE TITLE
Create card with created CIS classes inside 

### ISSUE THREAD

**Issue by HubbbaBubbba** [HubbbaBubbba/StackOps#7]

**Comment by HubbbaBubbba** [comment]
MongoDB data to card in search.ejs.

We have the search function working with hard coded data. We can print out all of our variable from the document (collection) on index.ejs. We need to figure out how to do the same on the search.ejs page. This will allow us to insert data from the MongoDB database as card.

**Comment by barrycumbie** [comment]
@HubbbaBubbba Roger that.
