### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by HubbbaBubbba** [HubbbaBubbba/StackOps#8]
Added header and footer:
Header, Login button (Goes to Login-form), Search button(non-functional), Admin Login button
Footer, Whatever our heart desires

**Comment by laurenmalone01** [comment]
https://w3schoolweb.com/how-to-create-a-footer-columns-in-html/

**Comment by HubbbaBubbba** [comment]
added Header/Footer
Can be used on course catalog page also, copy pasta
